export const PATH = {
  DASHBOARD: "DASHBOARD",
  NOTE: "NOTE",
  CUSTOMER: "CUSTOMER",
  PERMISSION: "PERMISSION",
  CATEGORY: "CATEGORY",
  TRASH: "TRASH",
  ACCOUT: "ACCOUT",
  CONTENT: "CONTENT",
  SYSTEM: "SYSTEM",
};
